from __future__ import annotations

from euclid.modules.calibration import (
    build_calibration_contract,
    evaluate_prediction_calibration,
)
from euclid.modules.candidate_fitting import (
    CandidateFitArtifactBundle,
    CandidateWindowFitResult,
    PersistentStateTransition,
    build_candidate_fit_artifacts,
    fit_candidate_development_windows,
    fit_candidate_window,
)
from euclid.modules.catalog_publishing import (
    LocalPublicationCatalogEntry,
    build_local_publication_catalog_entry,
    build_publication_record_manifest,
    build_run_result_manifest,
)
from euclid.modules.claims import (
    ClaimPublicationDecision,
    resolve_claim_publication,
)
from euclid.modules.evaluation import emit_point_prediction_artifact
from euclid.modules.evaluation_governance import (
    BaselineRegistry,
    ComparisonKey,
    ComparisonUniverse,
    EvaluationEventLog,
    EvaluationGovernance,
    ForecastComparisonPolicy,
    PredictiveGatePolicy,
    build_baseline_registry,
    build_comparison_key,
    build_comparison_universe,
    build_evaluation_event_log,
    build_evaluation_governance,
    build_forecast_comparison_policy,
    build_predictive_gate_policy,
    resolve_confirmatory_promotion_allowed,
)
from euclid.modules.external_evidence_ingestion import (
    ExternalEvidenceBundleResult,
    RegisteredExternalEvidenceBundle,
    build_external_evidence_bundle,
    register_external_evidence_bundle,
)
from euclid.modules.features import (
    FeatureSpec,
    FeatureView,
    default_feature_spec,
    materialize_feature_view,
)
from euclid.modules.gate_lifecycle import (
    ScorecardStatusDecision,
    resolve_scorecard_status,
)
from euclid.modules.ingestion import (
    AdmittedOrderedNumericData,
    ObservationRecord,
    ingest_csv_dataset,
    ingest_csv_observations,
    ingest_dataframe_dataset,
    ingest_parquet_dataset,
)
from euclid.modules.mechanistic_evidence import (
    MechanisticEvidenceEvaluation,
    RegisteredMechanisticEvidenceEvaluation,
    evaluate_mechanistic_evidence,
    register_mechanistic_evidence,
)
from euclid.modules.probabilistic_evaluation import (
    emit_probabilistic_prediction_artifact,
)
from euclid.modules.replay import (
    ReplayedOutcome,
    ReplayInspection,
    ReplayVerificationResult,
    actual_artifact_hashes,
    build_artifact_hash_records,
    build_replay_seed_records,
    build_replay_stage_order,
    build_reproducibility_bundle_manifest,
    build_runtime_environment_metadata,
    inspect_reproducibility_bundle,
    required_manifest_refs_for_publication,
    required_manifest_refs_from_run_result,
    resolve_candidate_or_abstention,
    resolve_point_score_result,
    resolve_prediction_artifact,
    resolve_scorecard,
    selected_candidate_ref,
    verify_replayed_outcome,
)
from euclid.modules.robustness import (
    AggregateMetricEvaluation,
    NullComparisonEvaluation,
    PerturbationFamilyEvaluation,
    PerturbationMetricEvaluation,
    PerturbationRunRecord,
    build_leakage_canary_manifest,
    build_leakage_canary_result_manifest,
    build_null_protocol_manifest,
    build_perturbation_protocol_manifest,
    build_retention_metric_manifest,
    build_robustness_report,
    build_surrogate_generator_manifest,
    evaluate_aggregate_metric_results,
    evaluate_null_comparison,
    evaluate_perturbation_family,
)
from euclid.modules.scoring import (
    PointComparatorEvaluationResult,
    evaluate_point_comparators,
    score_point_prediction_artifact,
    score_prediction_artifact,
    score_probabilistic_prediction_artifact,
)
from euclid.modules.shared_plus_local_decomposition import (
    SharedLocalFitSummary,
    fit_shared_plus_local_decomposition,
)
from euclid.modules.snapshotting import (
    FrozenDatasetSnapshot,
    SnapshotRow,
    freeze_dataset_snapshot,
)
from euclid.modules.split_planning import EvaluationPlan, build_evaluation_plan
from euclid.modules.timeguard import TimeSafetyAudit, audit_snapshot_time_safety

__all__ = [
    "EvaluationPlan",
    "AdmittedOrderedNumericData",
    "BaselineRegistry",
    "LocalPublicationCatalogEntry",
    "build_calibration_contract",
    "build_local_publication_catalog_entry",
    "build_publication_record_manifest",
    "build_run_result_manifest",
    "evaluate_prediction_calibration",
    "ComparisonKey",
    "ComparisonUniverse",
    "CandidateFitArtifactBundle",
    "CandidateWindowFitResult",
    "ClaimPublicationDecision",
    "EvaluationEventLog",
    "EvaluationGovernance",
    "ExternalEvidenceBundleResult",
    "FeatureSpec",
    "FeatureView",
    "ForecastComparisonPolicy",
    "FrozenDatasetSnapshot",
    "MechanisticEvidenceEvaluation",
    "ObservationRecord",
    "AggregateMetricEvaluation",
    "PointComparatorEvaluationResult",
    "PersistentStateTransition",
    "ReplayInspection",
    "ReplayVerificationResult",
    "ReplayedOutcome",
    "RegisteredExternalEvidenceBundle",
    "NullComparisonEvaluation",
    "PerturbationFamilyEvaluation",
    "PerturbationMetricEvaluation",
    "PerturbationRunRecord",
    "PredictiveGatePolicy",
    "RegisteredMechanisticEvidenceEvaluation",
    "ScorecardStatusDecision",
    "SnapshotRow",
    "TimeSafetyAudit",
    "audit_snapshot_time_safety",
    "build_candidate_fit_artifacts",
    "build_baseline_registry",
    "build_comparison_key",
    "build_comparison_universe",
    "build_evaluation_plan",
    "build_evaluation_event_log",
    "build_evaluation_governance",
    "build_forecast_comparison_policy",
    "build_artifact_hash_records",
    "build_leakage_canary_manifest",
    "build_leakage_canary_result_manifest",
    "build_null_protocol_manifest",
    "build_perturbation_protocol_manifest",
    "build_predictive_gate_policy",
    "build_external_evidence_bundle",
    "build_replay_seed_records",
    "build_replay_stage_order",
    "build_reproducibility_bundle_manifest",
    "build_retention_metric_manifest",
    "build_robustness_report",
    "build_surrogate_generator_manifest",
    "build_runtime_environment_metadata",
    "resolve_confirmatory_promotion_allowed",
    "resolve_claim_publication",
    "resolve_candidate_or_abstention",
    "resolve_point_score_result",
    "resolve_prediction_artifact",
    "resolve_scorecard",
    "resolve_scorecard_status",
    "required_manifest_refs_for_publication",
    "required_manifest_refs_from_run_result",
    "inspect_reproducibility_bundle",
    "selected_candidate_ref",
    "verify_replayed_outcome",
    "emit_point_prediction_artifact",
    "emit_probabilistic_prediction_artifact",
    "actual_artifact_hashes",
    "evaluate_aggregate_metric_results",
    "evaluate_null_comparison",
    "evaluate_point_comparators",
    "evaluate_perturbation_family",
    "evaluate_mechanistic_evidence",
    "default_feature_spec",
    "fit_candidate_development_windows",
    "fit_candidate_window",
    "freeze_dataset_snapshot",
    "ingest_csv_dataset",
    "ingest_csv_observations",
    "ingest_dataframe_dataset",
    "ingest_parquet_dataset",
    "materialize_feature_view",
    "register_mechanistic_evidence",
    "register_external_evidence_bundle",
    "score_prediction_artifact",
    "score_probabilistic_prediction_artifact",
    "score_point_prediction_artifact",
    "SharedLocalFitSummary",
    "fit_shared_plus_local_decomposition",
]
